### ISSUE TITLE
Inaccurate token count for a larger function

### ISSUE THREAD

**Issue by petrbrzek** [hmarr/openai-chat-tokens#3]
First of all, thanks for this library, I'm glad someone took the initiative. I want to implement this library in LangTale, but while testing I came across an example and found that the estimated tokens are unfortunately inaccurate. Here's the first case I found out. If I find more, I'll add them here.

Example function: https://langtale.ai/playground/p/GSaUrwtec0
Code for repro: https://runkit.com/petrbrzek/64cea8b68a118000084e4dc5

OpenAI API returns: `"prompt_tokens": 120`.
This library returns: 84 tokens.

**Comment by hmarr** [comment]
Glad to hear it's useful! I haven't implemented support for function calling with array parameters yet, so I'm guessing it's that. Feel free to submit a PR if you want, and if not I'll try to have a look when I have some time.

**Comment by petrbrzek** [comment]
It's here https://github.com/hmarr/openai-chat-tokens/pull/4.

**Comment by hmarr** [comment]
Thanks!
