### ISSUE TITLE
Account for token overhead of the `function_call` param

### ISSUE THREAD

**Issue by b0o** [hmarr/openai-chat-tokens#9]
First of all, I wanted to thank you for creating this project, it's been a huge help.

I noticed that the `promptTokensEstimate()` function doesn't take into account the `function_call` param to `openai.chat.completions.create()`. This means that the token count is:

- correct if `function_call` is `'auto'` or `undefined`
- under by `1` when `function_call` is `'none'`
- under by `4 + stringTokens(function_call.name)` when `function_call` is an object

It would be nice if openai-chat-tokens supported this natively.

In the mean time, here's a wrapper function I'm using:

```ts
import type { OpenAI } from 'openai'
import { promptTokensEstimate, stringTokens } from 'openai-chat-tokens'

export function calculateTokenCountForChat({
  messages,
  functions,
  function_call,
}: OpenAI.Chat.ChatCompletionCreateParamsNonStreaming | OpenAI.Chat.ChatCompletionCreateParamsStreaming): number {
  const promptTokens = promptTokensEstimate({ messages, functions })
  if (function_call && function_call !== 'auto') {
    const functionCallTokens = function_call === 'none' ? 1 : stringTokens(function_call.name) + 4
    return promptTokens + functionCallTokens
  }
  return promptTokens
}
```

**Comment by hmarr** [comment]
Thank you for the detailed issue report and PR @b0o! 🙌 

This will go out in the next release (v0.2.7) which I'll get published shortly.
